import { LightningElement, track } from 'lwc';

const IN_PROGRESS_ITEMS = [
    { id: 'ip-01', channel: 'cases', subject: 'Technical Assistance Bot',           caseNumber: '100783405', priority: 'Medium',   status: 'Working', assignedTo: 'Bay Assist Agent', isAgent: true,  routeBy: 'Direct to Agent', hasFlag: false, sentiment: 'neutral',   workSize: 5, isInterruptible: true,  handleTime: '4 m',    assignedTime: '22 Oct, 2025', speedToAnswer: '1:07',  acceptedTime: '22 Oct, 2025' },
    { id: 'ip-02', channel: 'chat',  subject: 'Technical Assistance Bot',           caseNumber: '100783406', priority: 'High',     status: 'Pending', assignedTo: 'Dana Bose',       isAgent: false, avatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg', routeBy: 'Skills-Based', routeByIcon: 'utility:skill', hasFlag: false, sentiment: 'good',      workSize: 2, isInterruptible: false, handleTime: '9 m',    assignedTime: '21 Sep, 2025', speedToAnswer: '0:44',  acceptedTime: '21 Sep, 2025' },
    { id: 'ip-03', channel: 'cases', subject: 'Product Recommendation Assistant',   caseNumber: '100783409', priority: '',         status: 'Active',  assignedTo: 'Fiona Patel', isAgent: false, avatarUrl: 'https://randomuser.me/api/portraits/women/68.jpg', routeBy: 'Product Knowled...', routeByIcon: 'utility:skill', hasFlag: false, sentiment: 'excellent', workSize: 8, isInterruptible: true,  handleTime: '1 m',    assignedTime: '17 Sep, 2025', speedToAnswer: '0:17',  acceptedTime: '17 Sep, 2025' },
    { id: 'ip-04', channel: 'call',  subject: 'Order Status Inquiry',               caseNumber: '100783412', priority: '',         status: 'Waiting', assignedTo: 'Sofia Yang',     isAgent: false, avatarUrl: 'https://randomuser.me/api/portraits/women/12.jpg', routeBy: 'SF Proactive Sup...', routeByIcon: 'utility:work_queue', hasFlag: true,  sentiment: 'neutral',   workSize: 3, isInterruptible: false, handleTime: '3 h',    assignedTime: '15 Sep, 2025', speedToAnswer: '1:10',  acceptedTime: '15 Sep, 2025' },
    { id: 'ip-05', channel: 'cases', subject: 'Subscription Management Support',    caseNumber: '100783415', priority: 'Medium',   status: 'Working', assignedTo: 'Tech Agentforce', isAgent: true,  routeBy: 'Direct to Agent', hasFlag: false, sentiment: 'good',      workSize: 6, isInterruptible: true,  handleTime: '3 m',    assignedTime: '9 Sep, 2025',  speedToAnswer: '—',     acceptedTime: '—' },
    { id: 'ip-06', channel: 'chat',  subject: 'Delivery Issue Resolution',          caseNumber: '100783418', priority: 'High',     status: 'Pending', assignedTo: 'Matthew Fox',    isAgent: false, avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg', routeBy: 'Most Available', routeByIcon: 'utility:skill', hasFlag: false, sentiment: 'bad',       workSize: 4, isInterruptible: false, handleTime: '44 m',   assignedTime: '4 Sep, 2025',  speedToAnswer: '0:22',  acceptedTime: '4 Sep, 2025' },
    { id: 'ip-07', channel: 'email', subject: 'Customer Upgrade Chart',             caseNumber: '100783421', priority: 'Medium',   status: 'Working', assignedTo: 'Social Media Ma...', isAgent: true, routeBy: 'Direct to Agent', hasFlag: false, sentiment: 'neutral',   workSize: 1, isInterruptible: true,  handleTime: '10 m',   assignedTime: '25 Aug, 2025', speedToAnswer: '1:02',  acceptedTime: '25 Aug, 2025' },
    { id: 'ip-08', channel: 'cases', subject: 'Agent Registration Form',            caseNumber: '100783424', priority: '',         status: 'Waiting', assignedTo: 'Grace Agent',    isAgent: true,  routeBy: 'Direct to Agent', hasFlag: true,  sentiment: 'excellent', workSize: 9, isInterruptible: false, handleTime: '7 m',    assignedTime: '21 Aug, 2025', speedToAnswer: '0:31',  acceptedTime: '21 Aug, 2025' },
    { id: 'ip-09', channel: 'chat',  subject: 'Feedback Collection Chat',           caseNumber: '100783427', priority: '',         status: 'Active',  assignedTo: 'Aisha Khan',     isAgent: false, avatarUrl: 'https://randomuser.me/api/portraits/women/63.jpg', routeBy: 'Round Robin', routeByIcon: 'utility:work_queue', hasFlag: false, sentiment: 'good',      workSize: 2, isInterruptible: true,  handleTime: '14 m',   assignedTime: '17 Aug, 2025', speedToAnswer: '0:55',  acceptedTime: '17 Aug, 2025' },
    { id: 'ip-10', channel: 'call',  subject: 'Feedback Collection Chat',           caseNumber: '100783430', priority: 'High',     status: 'Pending', assignedTo: 'Ethan Brooks',   isAgent: false, avatarUrl: 'https://randomuser.me/api/portraits/men/45.jpg', routeBy: 'Most Idle', routeByIcon: 'utility:work_queue', hasFlag: false, sentiment: 'terrible',  workSize: 7, isInterruptible: false, handleTime: '5 m',    assignedTime: '11 Aug, 2025', speedToAnswer: '1:20',  acceptedTime: '11 Aug, 2025' },
    { id: 'ip-11', channel: 'cases', subject: 'Feedback Collection Omni',           caseNumber: '100783433', priority: 'Medium',   status: 'Working', assignedTo: 'Marcus Cole',    isAgent: false, avatarUrl: 'https://randomuser.me/api/portraits/men/76.jpg', routeBy: 'Skills-Based', routeByIcon: 'utility:skill', hasFlag: false, sentiment: 'neutral',   workSize: 3, isInterruptible: true,  handleTime: '2 m',    assignedTime: '5 Aug, 2025',  speedToAnswer: '0:08',  acceptedTime: '5 Aug, 2025' },
    { id: 'ip-12', channel: 'cases', subject: 'Refund processing delay investigation', caseNumber: '100783436', priority: 'High',     status: 'Pending', assignedTo: 'Liam Anderson',  isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=12', routeBy: 'Skills-Based',  routeByIcon: 'utility:skill',      hasFlag: false, sentiment: 'bad',       workSize: 5, isInterruptible: false, handleTime: '12 m',   assignedTime: '3 Aug, 2025',  speedToAnswer: '0:38',  acceptedTime: '3 Aug, 2025' },
    { id: 'ip-13', channel: 'chat',  subject: 'Knowledge Base AI Assist',             caseNumber: '100783439', priority: '',         status: 'Active',  assignedTo: 'Knowledge Bot',  isAgent: true,  routeBy: 'Direct to Agent', routeByIcon: null,                                  hasFlag: false, sentiment: 'good',      workSize: 1, isInterruptible: true,  handleTime: '2 m',    assignedTime: '1 Aug, 2025',  speedToAnswer: '0:05',  acceptedTime: '1 Aug, 2025' },
    { id: 'ip-14', channel: 'email', subject: 'Warranty claim review request',         caseNumber: '100783442', priority: 'Medium',   status: 'Working', assignedTo: 'Olivia Bennett', isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=14', routeBy: 'Most Available', routeByIcon: 'utility:skill',      hasFlag: true,  sentiment: 'neutral',   workSize: 4, isInterruptible: true,  handleTime: '8 m',    assignedTime: '30 Jul, 2025', speedToAnswer: '1:02',  acceptedTime: '30 Jul, 2025' },
    { id: 'ip-15', channel: 'call',  subject: 'Account merge request',                 caseNumber: '100783445', priority: 'Critical', status: 'Pending', assignedTo: 'Routing Agent',  isAgent: true,  routeBy: 'Direct to Agent', routeByIcon: null,                                  hasFlag: true,  sentiment: 'terrible',  workSize: 9, isInterruptible: false, handleTime: '23 m',   assignedTime: '28 Jul, 2025', speedToAnswer: '0:11',  acceptedTime: '28 Jul, 2025' },
    { id: 'ip-16', channel: 'chat',  subject: 'Shipping address change after dispatch',caseNumber: '100783448', priority: '',         status: 'Waiting', assignedTo: 'Noah Carter',    isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=16', routeBy: 'Round Robin',    routeByIcon: 'utility:work_queue', hasFlag: false, sentiment: 'neutral',   workSize: 2, isInterruptible: true,  handleTime: '6 m',    assignedTime: '25 Jul, 2025', speedToAnswer: '0:27',  acceptedTime: '25 Jul, 2025' },
    { id: 'ip-17', channel: 'cases', subject: 'Product activation key not received',   caseNumber: '100783451', priority: 'Low',      status: 'Working', assignedTo: 'Activation Bot', isAgent: true,  routeBy: 'Direct to Agent', routeByIcon: null,                                  hasFlag: false, sentiment: 'good',      workSize: 1, isInterruptible: true,  handleTime: '1 m',    assignedTime: '23 Jul, 2025', speedToAnswer: '0:03',  acceptedTime: '23 Jul, 2025' },
    { id: 'ip-18', channel: 'messaging', subject: 'Two-factor reset locked account',   caseNumber: '100783454', priority: 'High',     status: 'Pending', assignedTo: 'Ava Thompson',   isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=18', routeBy: 'Skills-Based',   routeByIcon: 'utility:skill',      hasFlag: false, sentiment: 'bad',       workSize: 6, isInterruptible: false, handleTime: '15 m',   assignedTime: '21 Jul, 2025', speedToAnswer: '0:51',  acceptedTime: '21 Jul, 2025' },
    { id: 'ip-19', channel: 'cases', subject: 'Subscription renewal pricing question', caseNumber: '100783457', priority: 'Medium',   status: 'Active',  assignedTo: 'Renewal Agent',  isAgent: true,  routeBy: 'Direct to Agent', routeByIcon: null,                                  hasFlag: false, sentiment: 'neutral',   workSize: 3, isInterruptible: true,  handleTime: '4 m',    assignedTime: '18 Jul, 2025', speedToAnswer: '0:14',  acceptedTime: '18 Jul, 2025' },
    { id: 'ip-20', channel: 'email', subject: 'Bulk order export failing on download', caseNumber: '100783460', priority: '',         status: 'Working', assignedTo: 'Ethan Walker',   isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=20', routeBy: 'Most Idle',      routeByIcon: 'utility:work_queue', hasFlag: false, sentiment: 'good',      workSize: 4, isInterruptible: true,  handleTime: '9 m',    assignedTime: '15 Jul, 2025', speedToAnswer: '1:18',  acceptedTime: '15 Jul, 2025' },
    { id: 'ip-21', channel: 'call',  subject: 'VIP escalation — outage impact review', caseNumber: '100783463', priority: 'Critical', status: 'Working', assignedTo: 'Mia Robinson',   isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=22', routeBy: 'Skills-Based',   routeByIcon: 'utility:skill',      hasFlag: true,  sentiment: 'terrible',  workSize: 8, isInterruptible: false, handleTime: '1 h',    assignedTime: '12 Jul, 2025', speedToAnswer: '0:09',  acceptedTime: '12 Jul, 2025' },
    { id: 'ip-22', channel: 'chat',  subject: 'Tier upgrade preview eligibility',      caseNumber: '100783466', priority: 'Low',      status: 'Waiting', assignedTo: 'Upgrade Bot',    isAgent: true,  routeBy: 'Direct to Agent', routeByIcon: null,                                  hasFlag: false, sentiment: 'good',      workSize: 2, isInterruptible: true,  handleTime: '3 m',    assignedTime: '10 Jul, 2025', speedToAnswer: '0:06',  acceptedTime: '10 Jul, 2025' },
    { id: 'ip-23', channel: 'cases', subject: 'Replacement device tracking number',    caseNumber: '100783469', priority: '',         status: 'Pending', assignedTo: 'Logistics Bot',  isAgent: true,  routeBy: 'Direct to Agent', routeByIcon: null,                                  hasFlag: false, sentiment: 'neutral',   workSize: 3, isInterruptible: true,  handleTime: '5 m',    assignedTime: '8 Jul, 2025',  speedToAnswer: '0:02',  acceptedTime: '8 Jul, 2025' },
    { id: 'ip-24', channel: 'cases', subject: 'GDPR data export request',              caseNumber: '100783472', priority: 'High',     status: 'Pending', assignedTo: 'Isabella Reed',  isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=24', routeBy: 'Skills-Based',   routeByIcon: 'utility:skill',      hasFlag: true,  sentiment: 'bad',       workSize: 7, isInterruptible: false, handleTime: '32 m',   assignedTime: '5 Jul, 2025',  speedToAnswer: '0:44',  acceptedTime: '5 Jul, 2025' },
    { id: 'ip-25', channel: 'chat',  subject: 'Live chat handoff to specialist',       caseNumber: '100783475', priority: 'Medium',   status: 'Working', assignedTo: 'Lucas Bailey',   isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=26', routeBy: 'Most Available', routeByIcon: 'utility:skill',      hasFlag: false, sentiment: 'neutral',   workSize: 4, isInterruptible: true,  handleTime: '11 m',   assignedTime: '3 Jul, 2025',  speedToAnswer: '0:19',  acceptedTime: '3 Jul, 2025' },
    { id: 'ip-26', channel: 'email', subject: 'Compliance disclosure follow-up',       caseNumber: '100783478', priority: 'Low',      status: 'Active',  assignedTo: 'Charlotte Ross', isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=28', routeBy: 'Queue-based',    routeByIcon: 'utility:work_queue', hasFlag: false, sentiment: 'good',      workSize: 2, isInterruptible: true,  handleTime: '7 m',    assignedTime: '1 Jul, 2025',  speedToAnswer: '0:33',  acceptedTime: '1 Jul, 2025' },
    { id: 'ip-27', channel: 'call',  subject: 'Repeat billing complaint — third call', caseNumber: '100783481', priority: 'High',     status: 'Working', assignedTo: 'Triage Agent',   isAgent: true,  routeBy: 'Direct to Agent', routeByIcon: null,                                  hasFlag: true,  sentiment: 'terrible',  workSize: 6, isInterruptible: false, handleTime: '18 m',   assignedTime: '28 Jun, 2025', speedToAnswer: '0:07',  acceptedTime: '28 Jun, 2025' },
    { id: 'ip-28', channel: 'cases', subject: 'Promo code stacking eligibility check', caseNumber: '100783484', priority: '',         status: 'Working', assignedTo: 'Henry Morgan',   isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=30', routeBy: 'Round Robin',    routeByIcon: 'utility:work_queue', hasFlag: false, sentiment: 'neutral',   workSize: 1, isInterruptible: true,  handleTime: '2 m',    assignedTime: '25 Jun, 2025', speedToAnswer: '0:24',  acceptedTime: '25 Jun, 2025' },
    { id: 'ip-29', channel: 'chat',  subject: 'Onboarding tour assistance',            caseNumber: '100783487', priority: 'Medium',   status: 'Active',  assignedTo: 'Onboarding Bot', isAgent: true,  routeBy: 'Direct to Agent', routeByIcon: null,                                  hasFlag: false, sentiment: 'excellent', workSize: 3, isInterruptible: true,  handleTime: '4 m',    assignedTime: '22 Jun, 2025', speedToAnswer: '0:08',  acceptedTime: '22 Jun, 2025' },
    { id: 'ip-30', channel: 'cases', subject: 'Cancellation reconsideration outreach', caseNumber: '100783490', priority: 'Medium',   status: 'Pending', assignedTo: 'Emma Sullivan',  isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=32', routeBy: 'Skills-Based',   routeByIcon: 'utility:skill',      hasFlag: false, sentiment: 'good',      workSize: 5, isInterruptible: true,  handleTime: '13 m',   assignedTime: '19 Jun, 2025', speedToAnswer: '0:47',  acceptedTime: '19 Jun, 2025' },
    { id: 'ip-31', channel: 'messaging', subject: 'Mobile app crash on payment screen',caseNumber: '100783493', priority: 'High',     status: 'Working', assignedTo: 'Mason Hughes',   isAgent: false, avatarUrl: 'https://i.pravatar.cc/64?img=33', routeBy: 'Most Available', routeByIcon: 'utility:skill',      hasFlag: true,  sentiment: 'bad',       workSize: 7, isInterruptible: false, handleTime: '21 m',   assignedTime: '16 Jun, 2025', speedToAnswer: '0:15',  acceptedTime: '16 Jun, 2025' },
];

const WORK_ITEMS = [
    { id: 'wi-a', customer: 'Sarah Mitchell', subject: 'Billing dispute on recent invoice — overcharge on plan upgrade',  caseNumber: '100847321', status: 'Working', priority: 'Medium', channel: 'cases', queue: 'Billing', hasFlag: false },
    { id: 'wi-b', customer: 'James Okafor',   subject: 'Unable to access account after password reset loop',                caseNumber: '100912456', status: 'Pending', priority: 'High',   channel: 'cases', queue: 'Billing', hasFlag: true  },
    { id: 'wi-c', customer: 'Priya Nair',     subject: 'Refund request for duplicate transaction on 14 Apr',                caseNumber: '100863017', status: 'Working', priority: 'Medium', channel: 'cases', queue: 'Billing', hasFlag: false },
    { id: 'wi-d', customer: 'Carlos Reyes',   subject: 'Live chat: card declined at checkout, needs payment method update', caseNumber: '100779834', status: 'Active',  priority: 'Low',    channel: 'chat',  queue: 'Billing', hasFlag: true  },
    { id: 'wi-e', customer: 'Hannah Brooks',  subject: 'Subscription auto-renewed despite cancellation email',               caseNumber: '101023881', status: 'Pending', priority: 'High',   channel: 'cases', queue: 'Renewals', hasFlag: false },
    { id: 'wi-f', customer: 'Ahmed Hassan',   subject: 'Voice call: device repeatedly disconnects from wifi',                caseNumber: '101145672', status: 'Working', priority: 'Medium', channel: 'call',  queue: 'Tech',    hasFlag: false },
    { id: 'wi-g', customer: 'Lena Park',      subject: 'Loyalty points missing after qualifying purchase',                   caseNumber: '101207334', status: 'Active',  priority: 'Low',    channel: 'cases', queue: 'Loyalty', hasFlag: false },
    { id: 'wi-h', customer: 'Diego Alvarez',  subject: 'Bulk return shipment status — awaiting carrier confirmation',        caseNumber: '101289005', status: 'Waiting', priority: 'Medium', channel: 'cases', queue: 'Returns', hasFlag: true  },
];

const REPS_DATA = [
    { id: 1,  name: 'Gilda Ann Thomas',  status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:15am', hasFlag: true,  workSummary: '3 Cases 1 Message', channels: ['chat','call','cases'], login: '2m 5s',   state: '5m 3s',   capacityP: 100, capacityI: 100, accept: '3m 5s',   workload: '0/20', acw: '2m 4s',   queues: ['Billing','Chat','+3'],         skills: ['Billing','Refunds','+4'],            children: WORK_ITEMS },
    { id: 2,  name: 'Jerome Bell',        status: 'break',   statusLabel: 'On Break',   statusTime: 'Since 9:15am', hasFlag: false, workSummary: '2 Cases',           channels: ['call','cases'],       login: '10m 20s', state: '10m 20s', capacityP: 20,  capacityI: 35,  accept: '44m',     workload: '0/20', acw: '5m 34s',  queues: ['Sales','Returns','+2'],        skills: ['Sales','Spanish','+1'],              children: WORK_ITEMS.slice(0, 2) },
    { id: 3,  name: 'Devon Lane',         status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:15am', hasFlag: true,  workSummary: '3 Cases 1 Message', channels: ['chat','call','cases'], login: '2m 5s',   state: '5m 3s',   capacityP: 100, capacityI: 100, accept: '3m 5s',   workload: '0/20', acw: '2m 4s',   queues: ['Tech','Escalations','+4'],     skills: ['Technical','Tier 3','+3'],           children: WORK_ITEMS },
    { id: 4,  name: 'Arlene McCoy',       status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:15am', hasFlag: false, workSummary: '1 Case',            channels: ['call','cases'],       login: '8m 12s',  state: '14m 45s', capacityP: 100, capacityI: 40,  accept: '14m 45s', workload: '0/20', acw: '44m',     queues: ['VIP','Loyalty','+1'],          skills: ['Account Mgmt','French','+2'],        children: WORK_ITEMS.slice(0, 1) },
    { id: 5,  name: 'Floyd Miles',        status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:15am', hasFlag: true,  workSummary: '3 Cases 1 Message', channels: ['chat','call','cases'], login: '2m 5s',   state: '5m 3s',   capacityP: 100, capacityI: 100, accept: '3m 5s',   workload: '0/20', acw: '2m 4s',   queues: ['Onboarding','Chat','+3'],      skills: ['Onboarding','Wireless','+3'],        children: WORK_ITEMS },
    { id: 6,  name: 'Savannah Nguyen',    status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:15am', hasFlag: false, workSummary: '4 Cases',           channels: ['cases'],              login: '10m 20s', state: '1h 26m',  capacityP: 50,  capacityI: 100, accept: '5m 34s',  workload: '0/20', acw: '1h 26m',  queues: ['Cancellations','Tier 2','+2'], skills: ['Retention','Account Recovery','+2'], children: WORK_ITEMS },
    { id: 7,  name: 'Leslie Alexander',   status: 'break',   statusLabel: 'On Break',   statusTime: 'Since 9:15am', hasFlag: false, workSummary: '2 Messages',        channels: ['chat'],               login: '44m',     state: '8m 12s',  capacityP: 30,  capacityI: 50,  accept: '1h 26m',  workload: '0/20', acw: '10m 20s', queues: ['Chat','Support','+1'],         skills: ['Chat','Spanish','+2'],               children: WORK_ITEMS.slice(0, 2) },
    { id: 8,  name: 'Robert Fox',         status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:15am', hasFlag: false, workSummary: '3 Cases 1 Message', channels: ['chat','call','cases'], login: '5m 34s',  state: '10m 20s', capacityP: 50,  capacityI: 20,  accept: '7m 25s',  workload: '0/20', acw: '10m 20s', queues: ['Tier 1','Sales','+3'],         skills: ['Sales','Premium Support','+2'],      children: WORK_ITEMS },
    { id: 9,  name: 'Theresa Webb',       status: 'offline', statusLabel: 'Offline',    statusTime: 'Since 9:15am', hasFlag: false, workSummary: '1 Message',         channels: ['chat','call'],        login: '9m 02s',  state: '9m 02s',  capacityP: 30,  capacityI: 80,  accept: '14m 45s', workload: '0/20', acw: '5m 34s',  queues: ['Refunds','Billing','+1'],      skills: ['Refunds','Billing','+1'],            children: WORK_ITEMS.slice(0, 1) },
    { id: 10, name: 'Marvin McKinney',    status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:15am', hasFlag: false, workSummary: '1 Call',            channels: ['call','cases'],       login: '1h 26m',  state: '5m 34s',  capacityP: 40,  capacityI: 50,  accept: '7m 25s',  workload: '0/20', acw: '44m',     queues: ['Tech','VIP','+2'],             skills: ['Technical','Tier 2','+2'],           children: WORK_ITEMS.slice(0, 1) },
    { id: 11, name: 'Kylie Jenner',       status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:15am', hasFlag: false, workSummary: '1 Call',            channels: ['call','cases'],       login: '1h 26m',  state: '5m 34s',  capacityP: 40,  capacityI: 50,  accept: '7m 25s',  workload: '0/20', acw: '44m',     queues: ['Sales','Loyalty','+3'],        skills: ['Sales','German','+3'],               children: WORK_ITEMS.slice(0, 1) },
    { id: 12, name: 'Tom Hanks',          status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:15am', hasFlag: false, workSummary: '1 Call',            channels: ['call','cases'],       login: '1h 26m',  state: '5m 34s',  capacityP: 40,  capacityI: 50,  accept: '7m 25s',  workload: '0/20', acw: '44m',     queues: ['Escalations','Tier 3','+1'],   skills: ['Escalations','Account Mgmt','+1'],   children: WORK_ITEMS.slice(0, 1) },
    { id: 13, name: 'Eleanor Pena',       status: 'online',  statusLabel: 'All Online', statusTime: 'Since 8:42am', hasFlag: false, workSummary: '2 Cases',           channels: ['chat','cases'],       login: '3h 12m',  state: '12m 04s', capacityP: 80,  capacityI: 60,  accept: '4m 18s',  workload: '0/20', acw: '6m 12s',  queues: ['Renewals','Loyalty','+2'],     skills: ['Retention','Account Mgmt','+2'],     children: WORK_ITEMS.slice(0, 2) },
    { id: 14, name: 'Wade Warren',        status: 'break',   statusLabel: 'On Break',   statusTime: 'Since 11:02am',hasFlag: false, workSummary: '1 Case',            channels: ['call'],               login: '4h 47m',  state: '15m 20s', capacityP: 0,   capacityI: 0,   accept: '—',       workload: '0/20', acw: '9m 02s',  queues: ['Tech','Tier 2','+1'],          skills: ['Technical','Diagnostics','+1'],      children: WORK_ITEMS.slice(2, 4) },
    { id: 15, name: 'Brooklyn Simmons',   status: 'online',  statusLabel: 'All Online', statusTime: 'Since 7:55am', hasFlag: true,  workSummary: '4 Cases 2 Messages',channels: ['chat','call','cases'], login: '5h 03m',  state: '22m 47s', capacityP: 90,  capacityI: 100, accept: '2m 11s',  workload: '0/20', acw: '3m 18s',  queues: ['VIP','Billing','+3'],          skills: ['Premium Support','Billing','+3'],    children: WORK_ITEMS },
    { id: 16, name: 'Kristin Watson',     status: 'offline', statusLabel: 'Offline',    statusTime: 'Since 6:30am', hasFlag: false, workSummary: '0 Cases',           channels: ['cases'],              login: '8h 41m',  state: '8h 41m',  capacityP: 0,   capacityI: 0,   accept: '—',       workload: '0/20', acw: '—',       queues: ['Billing','Refunds'],           skills: ['Billing','Refunds'],                 children: [] },
    { id: 17, name: 'Cody Fisher',        status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:30am', hasFlag: false, workSummary: '3 Cases',           channels: ['call','cases'],       login: '2h 58m',  state: '9m 12s',  capacityP: 70,  capacityI: 85,  accept: '5m 09s',  workload: '0/20', acw: '4m 33s',  queues: ['Sales','Onboarding','+2'],     skills: ['Sales','Onboarding','+2'],           children: WORK_ITEMS.slice(0, 3) },
    { id: 18, name: 'Cameron Williamson', status: 'online',  statusLabel: 'All Online', statusTime: 'Since 10:11am',hasFlag: false, workSummary: '1 Message',         channels: ['chat'],               login: '1h 44m',  state: '6m 50s',  capacityP: 100, capacityI: 75,  accept: '3m 02s',  workload: '0/20', acw: '2m 18s',  queues: ['Chat','Support','+1'],         skills: ['Chat','German','+1'],                children: WORK_ITEMS.slice(4, 5) },
    { id: 19, name: 'Jenny Wilson',       status: 'break',   statusLabel: 'On Break',   statusTime: 'Since 11:30am',hasFlag: false, workSummary: '2 Cases',           channels: ['cases'],              login: '5h 22m',  state: '20m 10s', capacityP: 0,   capacityI: 0,   accept: '—',       workload: '0/20', acw: '7m 41s',  queues: ['Refunds','Returns','+2'],      skills: ['Refunds','Returns','+1'],            children: WORK_ITEMS.slice(5, 7) },
    { id: 20, name: 'Esther Howard',      status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:00am', hasFlag: true,  workSummary: '5 Cases 1 Message', channels: ['chat','call','cases'], login: '4h 18m',  state: '14m 02s', capacityP: 100, capacityI: 90,  accept: '1m 47s',  workload: '0/20', acw: '5m 50s',  queues: ['Escalations','VIP','+3'],      skills: ['Escalations','Premium','+3'],        children: WORK_ITEMS },
    { id: 21, name: 'Guy Hawkins',        status: 'offline', statusLabel: 'Offline',    statusTime: 'Since 5:00am', hasFlag: false, workSummary: '0 Cases',           channels: ['call','cases'],       login: '9h 15m',  state: '9h 15m',  capacityP: 0,   capacityI: 0,   accept: '—',       workload: '0/20', acw: '—',       queues: ['Tier 1','Sales'],              skills: ['Sales','Cold Calls'],                children: [] },
    { id: 22, name: 'Bessie Cooper',      status: 'online',  statusLabel: 'All Online', statusTime: 'Since 8:15am', hasFlag: false, workSummary: '2 Cases 1 Call',    channels: ['call','cases'],       login: '3h 50m',  state: '11m 17s', capacityP: 60,  capacityI: 70,  accept: '4m 22s',  workload: '0/20', acw: '6m 04s',  queues: ['Cancellations','Tier 2','+1'], skills: ['Retention','Negotiation','+1'],      children: WORK_ITEMS.slice(0, 2) },
    { id: 23, name: 'Albert Flores',      status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:45am', hasFlag: false, workSummary: '1 Case',            channels: ['cases'],              login: '2h 22m',  state: '7m 33s',  capacityP: 50,  capacityI: 100, accept: '6m 11s',  workload: '0/20', acw: '8m 25s',  queues: ['Tech','Diagnostics','+1'],     skills: ['Technical','Tier 3','+2'],           children: WORK_ITEMS.slice(1, 2) },
    { id: 24, name: 'Ronald Richards',    status: 'break',   statusLabel: 'On Break',   statusTime: 'Since 10:45am',hasFlag: false, workSummary: '1 Message',         channels: ['chat','cases'],       login: '6h 02m',  state: '18m 09s', capacityP: 0,   capacityI: 0,   accept: '—',       workload: '0/20', acw: '4m 17s',  queues: ['Chat','Billing','+1'],         skills: ['Chat','Billing','+1'],               children: WORK_ITEMS.slice(2, 3) },
    { id: 25, name: 'Dianne Russell',     status: 'online',  statusLabel: 'All Online', statusTime: 'Since 7:30am', hasFlag: false, workSummary: '3 Cases 1 Call',    channels: ['chat','call','cases'], login: '5h 11m',  state: '13m 44s', capacityP: 85,  capacityI: 95,  accept: '2m 33s',  workload: '0/20', acw: '3m 22s',  queues: ['VIP','Loyalty','+3'],          skills: ['Premium','French','+3'],             children: WORK_ITEMS.slice(0, 3) },
    { id: 26, name: 'Jacob Jones',        status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:20am', hasFlag: true,  workSummary: '2 Cases',           channels: ['call','cases'],       login: '3h 33m',  state: '10m 02s', capacityP: 75,  capacityI: 50,  accept: '3m 48s',  workload: '0/20', acw: '5m 11s',  queues: ['Escalations','Tier 3','+2'],   skills: ['Escalations','Diagnostics','+2'],    children: WORK_ITEMS.slice(5, 7) },
    { id: 27, name: 'Annette Black',      status: 'online',  statusLabel: 'All Online', statusTime: 'Since 8:50am', hasFlag: false, workSummary: '1 Message',         channels: ['chat'],               login: '2h 41m',  state: '5m 28s',  capacityP: 100, capacityI: 65,  accept: '4m 01s',  workload: '0/20', acw: '2m 47s',  queues: ['Chat','Support'],              skills: ['Chat','Spanish','+1'],               children: WORK_ITEMS.slice(3, 4) },
    { id: 28, name: 'Courtney Henry',     status: 'offline', statusLabel: 'Offline',    statusTime: 'Since 4:15am', hasFlag: false, workSummary: '0 Cases',           channels: ['cases'],              login: '10h 20m', state: '10h 20m', capacityP: 0,   capacityI: 0,   accept: '—',       workload: '0/20', acw: '—',       queues: ['Billing','Refunds'],           skills: ['Billing','Refunds'],                 children: [] },
    { id: 29, name: 'Darlene Robertson',  status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:05am', hasFlag: false, workSummary: '4 Cases 2 Messages',channels: ['chat','call','cases'], login: '4h 27m',  state: '16m 50s', capacityP: 95,  capacityI: 80,  accept: '2m 18s',  workload: '0/20', acw: '4m 09s',  queues: ['Onboarding','VIP','+3'],       skills: ['Onboarding','Premium','+3'],         children: WORK_ITEMS },
    { id: 30, name: 'Ralph Edwards',      status: 'break',   statusLabel: 'On Break',   statusTime: 'Since 11:20am',hasFlag: false, workSummary: '1 Case',            channels: ['cases'],              login: '7h 14m',  state: '25m 11s', capacityP: 0,   capacityI: 0,   accept: '—',       workload: '0/20', acw: '11m 47s', queues: ['Returns','Refunds','+1'],      skills: ['Returns','Refunds','+1'],            children: WORK_ITEMS.slice(7, 8) },
    { id: 31, name: 'Jane Cooper',        status: 'online',  statusLabel: 'All Online', statusTime: 'Since 8:25am', hasFlag: false, workSummary: '3 Cases 1 Call',    channels: ['call','cases'],       login: '5h 49m',  state: '8m 17s',  capacityP: 65,  capacityI: 100, accept: '5m 03s',  workload: '0/20', acw: '6m 38s',  queues: ['Sales','Loyalty','+2'],        skills: ['Sales','Italian','+2'],              children: WORK_ITEMS.slice(0, 3) },
    { id: 32, name: 'Pamela Howard',      status: 'online',  statusLabel: 'All Online', statusTime: 'Since 9:55am', hasFlag: true,  workSummary: '2 Cases',           channels: ['chat','cases'],       login: '2h 06m',  state: '9m 45s',  capacityP: 100, capacityI: 100, accept: '1m 58s',  workload: '0/20', acw: '3m 03s',  queues: ['Escalations','VIP','+2'],      skills: ['Escalations','Premium','+2'],        children: WORK_ITEMS.slice(0, 2) },
];

export default class ServiceReps extends LightningElement {
    activeTab = 'service-reps';
    reps = REPS_DATA;
    @track aiFilterActive = false;
    @track humanFilterActive = false;

    get inProgressItems() {
        if (this.aiFilterActive)    return IN_PROGRESS_ITEMS.filter(i => i.isAgent);
        if (this.humanFilterActive) return IN_PROGRESS_ITEMS.filter(i => !i.isAgent);
        return IN_PROGRESS_ITEMS;
    }

    get inProgressCount() {
        return this.inProgressItems.length;
    }

    get aiFilterVariant() {
        return this.aiFilterActive ? 'brand' : 'border-filled';
    }

    get humanFilterVariant() {
        return this.humanFilterActive ? 'brand' : 'border-filled';
    }

    handleTabChange(event) {
        this.activeTab = event.target.value;
    }

    handleAiFilterToggle() {
        this.aiFilterActive = !this.aiFilterActive;
        if (this.aiFilterActive) this.humanFilterActive = false;
    }

    handleHumanFilterToggle() {
        this.humanFilterActive = !this.humanFilterActive;
        if (this.humanFilterActive) this.aiFilterActive = false;
    }
}
